In [2]:
import pandas as pd
import numpy as mp
import os

In [9]:
file = os.path.join("Resources", "movie_scores.csv")
df = pd.read_csv(file)
df.head(2)

,FILM,RottenTomatoes,RottenTomatoes_User,Metacritic,Metacritic_User,IMDB,Fandango_Stars,Fandango_Ratingvalue,RT_norm,RT_user_norm,...,IMDB_norm,RT_norm_round,RT_user_norm_round,Metacritic_norm_round,Metacritic_user_norm_round,IMDB_norm_round,Metacritic_user_vote_count,IMDB_user_vote_count,Fandango_votes,Fandango_Difference
0,Avengers: Age of Ultron (2015),74,86,66,7.1,7.8,5.0,4.5,3.70,4.3,...,3.90,3.5,4.5,3.5,3.5,4.0,1330,271107,14846,0.5
1,Cinderella (2015),85,80,67,7.5,7.1,5.0,4.5,4.25,4.0,...,3.55,4.5,4.0,3.5,4.0,3.5,249,65709,12640,0.5

In [13]:
df.dtypes

FILM                           object
RottenTomatoes                  int64
RottenTomatoes_User             int64
Metacritic                      int64
Metacritic_User               float64
IMDB                          float64
Fandango_Stars                float64
Fandango_Ratingvalue          float64
RT_norm                       float64
RT_user_norm                  float64
Metacritic_norm               float64
Metacritic_user_nom           float64
IMDB_norm                     float64
RT_norm_round                 float64
RT_user_norm_round            float64
Metacritic_norm_round         float64
Metacritic_user_norm_round    float64
IMDB_norm_round               float64
Metacritic_user_vote_count      int64
IMDB_user_vote_count            int64
Fandango_votes                  int64
Fandango_Difference           float64
dtype: object

In [21]:
df_imdb = df.loc[df["IMDB"]>=7, ["FILM", "IMDB", "IMDB_norm", "IMDB_norm_round", "IMDB_user_vote_count"]]

In [22]:
df_imdb

,FILM,IMDB,IMDB_norm,IMDB_norm_round,IMDB_user_vote_count
0,Avengers: Age of Ultron (2015),7.8,3.90,4.0,271107
1,Cinderella (2015),7.1,3.55,3.5,65709
2,Ant-Man (2015),7.8,3.90,4.0,103660
5,The Water Diviner (2015),7.2,3.60,3.5,39373
8,Shaun the Sheep Movie (2015),7.4,3.70,3.5,12227
...,...,...,...,...,...
140,Inside Out (2015),8.6,4.30,4.5,96252
141,Mr. Holmes (2015),7.4,3.70,3.5,7367
142,'71 (2015),7.2,3.60,3.5,24116
143,"Two Days, One Night (2014)",7.4,3.70,3.5,24345
144,Gett: The Trial of Viviane Amsalem (2015),7.8,3.90,4.0,1955

In [35]:
df_imdb_lesspopular = df.loc[(df["IMDB"]>=7) & (df["IMDB_user_vote_count"]<20000), ["FILM", "IMDB", "IMDB_norm", "IMDB_norm_round", "IMDB_user_vote_count"]]

In [36]:
df_imdb_lesspopular.head(-5)

,FILM,IMDB,IMDB_norm,IMDB_norm_round,IMDB_user_vote_count
8,Shaun the Sheep Movie (2015),7.4,3.70,3.5,12227
9,Love & Mercy (2015),7.8,3.90,4.0,5367
10,Far From The Madding Crowd (2015),7.2,3.60,3.5,12129
20,"McFarland, USA (2015)",7.5,3.75,4.0,13769
29,The End of the Tour (2015),7.9,3.95,4.0,1320
30,Red Army (2015),7.7,3.85,4.0,2275
31,When Marnie Was There (2015),7.8,3.90,4.0,4160
32,The Hunting Ground (2015),7.5,3.75,4.0,1196
41,Timbuktu (2015),7.2,3.60,3.5,6246
43,The Diary of a Teenage Girl (2015),7.0,3.50,3.5,1107
66,The Gift (2015),7.6,3.80,4.0,10891
68,Monkey Kingdom (2015),7.3,3.65,3.5,883
70,Seymour: An Introduction (2015),7.7,3.85,4.0,243
71,The Wrecking Crew (2015),7.8,3.90,4.0,732
76,Straight Outta Compton (2015),8.4,4.20,4.0,15982
85,Little Boy (2015),7.4,3.70,3.5,5927
86,Me and Earl and The Dying Girl (2015),8.2,4.10,4.0,5269
92,Dope (2015),7.5,3.75,4.0,4911
95,The Salt of the Earth (2015),8.4,4.20,4.0,6605
96,Song of the Sea (2014),8.2,4.10,4.0,14067
109,The 100-Year-Old Man Who Climbed Out the Windo...,7.1,3.55,3.5,17237
117,Testament of Youth (2015),7.3,3.65,3.5,5495
118,Infinitely Polar Bear (2015),7.2,3.60,3.5,1062
119,Phoenix (2015),7.2,3.60,3.5,3687
120,The Wolfpack (2015),7.1,3.55,3.5,1488
121,The Stanford Prison Experiment (2015),7.1,3.55,3.5,950
122,Tangerine (2015),7.4,3.70,3.5,696
126,Woman in Gold (2015),7.4,3.70,3.5,17957